version: '3.2'
services:
  atlas-api-server:
    restart: always
    build:
      context: .
    ports:
      - 80:8080
    volumes:
      - '.:/atlas'
    depends_on:
      - kafka

  kafka:
    image: spotify/kafka
    ports:
      - 9092:9092
      - 2181:2181
    environment:
      TOPICS: test-topic
      ADVERTISED_HOST: 192.168.100.10